"""empty message

Revision ID: 3d96d472b703
Revises: 3df358245ba5
Create Date: 2022-09-08 20:21:22.974620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d96d472b703'
down_revision = '3df358245ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_ibfk_3', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'planets', ['planet_id'], ['id'])
    op.drop_column('favorites', 'planeta_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planeta_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_ibfk_3', 'favorites', 'planets', ['planeta_id'], ['id'])
    op.drop_column('favorites', 'planet_id')
    # ### end Alembic commands ###
