"""empty message

Revision ID: 3df358245ba5
Revises: 526d81d50fc9
Create Date: 2022-09-08 20:05:48.901772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df358245ba5'
down_revision = '526d81d50fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planeta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'planets', ['planeta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'planeta_id')
    # ### end Alembic commands ###
