"""empty message

Revision ID: bb915c6a7fb9
Revises: d962fd4a71ae
Create Date: 2022-09-08 19:07:11.395246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb915c6a7fb9'
down_revision = 'd962fd4a71ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_ibfk_2', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'planeta_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planeta_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_ibfk_2', 'favorites', 'planets', ['planeta_id'], ['id'])
    # ### end Alembic commands ###
