"""empty message

Revision ID: f77641b128c2
Revises: 705f4bdceb70
Create Date: 2022-09-08 15:10:54.584415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77641b128c2'
down_revision = '705f4bdceb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('people_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'people', ['people_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'people_id')
    # ### end Alembic commands ###
